"""add resend rate limiting fields to user

Revision ID: 0b96519e2e60
Revises: 9a01f9570f86
Create Date: 2025-07-02 13:06:02.711997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b96519e2e60'
down_revision: Union[str, Sequence[str], None] = '9a01f9570f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resend_cooldown_seconds', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_code_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('resend_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resend_count')
    op.drop_column('users', 'last_code_sent_at')
    op.drop_column('users', 'resend_cooldown_seconds')
    # ### end Alembic commands ###
