"""remove resend_count from user

Revision ID: 480dbd148350
Revises: 0b96519e2e60
Create Date: 2025-07-04 16:40:59.417870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480dbd148350'
down_revision: Union[str, Sequence[str], None] = '0b96519e2e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resend_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resend_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
