"""remove time_spent and notes from activities table

Revision ID: b080fead1ec8
Revises: acknowledge_tables_001
Create Date: 2025-08-19 13:18:36.187495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b080fead1ec8'
down_revision: Union[str, Sequence[str], None] = 'acknowledge_tables_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'time_spent')
    op.drop_column('activities', 'notes')
    op.drop_column('users', 'oauth_picture')
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('oauth_provider_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('oauth_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('time_spent', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
